### ISSUE TITLE
TiCon Intergration

### ISSUE THREAD

**Issue by squirrelkiller** [KnightMiner/Ceramics#1]
Ceramic tool parts. This must be.

**Comment by KnightMiner** [comment]
There will be bucket filling integration once we decide how we want to allow extending the bucket recipe, so I'll consider clay tool parts.

Only issue is it ends up like gold where you would be making tools from a defined cast material

**Comment by squirrelkiller** [comment]
Maybe make it so you make the parts from soft clay on the part builder, then you fire them?

**Comment by KnightMiner** [comment]
Yeah, that would definitely be interesting. Just need to check how much Tinkers would support it (as if I remember correctly the repair material and creation material are the same)

**Comment by InsomniaKitten** [comment]
I don't know if you still plan on working on this, but my suggestion would be to do something similar to how Tinkers' does slime, where you craft the unfired clay into a block of some sort, then smelt it into a 'clay mould' or something, which could be used in the part builder like the slime crystals.

**Comment by KnightMiner** [comment]
For the record, this is blocked by MinecraftForge/MinecraftForge#3141, as I cannot currently use NBT in smelting recipes.

**Comment by InsomniaKitten** [comment]
I don't understand how it would need NBT data? It would work the same way all of the other clay items do. Craft an unfired version, smelt it into something else. Then use that smelted item as the material for tool parts.

**Comment by KnightMiner** [comment]
Because I need to be able to use Tinkers Construct tool parts to avoid adding every single tool part manually (as I want automatic compat). Tinkers uses NBT to keep track of materials for the part, so currently it allows any part type to smelt into clay instead of just raw clay

**Comment by Syndaryl** [comment]
Alternate approach suggestion:
Stick _really_ close to the slime comparison, and make your "clay crystal" (and porcelain crystal?) an actual crafting material, rather than crafting clay into unfired tinkers parts. The clay crystal could be made any complicated way you want, including furnace cooking, you just produce the item "clay crystal", which is the actual crafting material.

Then the repair material would be more clay crystals.

"Clay crystal" and "porcelain crystal" being used here as a stand in for whatever you want to call it. I'd consider looking at the baked clay tiles we use to make armor as the crafting material for clay, for example.

You could do the fancy raw-clay-part -> firing -> final clay part later, after forge gets its act together.

**Comment by KnightMiner** [comment]
As of Minecraft 1.14, furnace recipes use ingredients now, so I can make NBT recipes. As a result, I will be reconsidering this feature. I am thinking about adding clay tools directly to this mod as well.

**Comment by BedrockLegends** [comment]
Speak of this issue, is Tinker's being released soon for 1.15. I see the title shows Ticon Integration but we dont have Tinkers for 1.15 yet

**Comment by KnightMiner** [comment]
This is entirely the wrong place for that. I recommend you avoid asking for updates on unrelated forums.

**Comment by KnightMiner** [comment]
Closing this as I have decided against a Tinkers part, better suited for a TiC addon such as Tinkers Complement
