### ISSUE TITLE
[1.12.2] Compact with certain Animania milk

### ISSUE THREAD

**Issue by SeriousCreeper** [KnightMiner/Ceramics#27]
Heya,

i went through some old tickets on both here and the animania github where there was some talk about making the buckets work with animania animals. 

If they provide normal milk, the clay buckets work no problem. 

However if you try to milk anything with special milk (example: Goat Milk), the bucket doesn't work. I milk them using an iron bucket, place the liquid in the world, and pick it up with the ceramic bucket no problem though. But right clicking the goat itself doesn't give me the milk bucket. 

Is this something that could be implemented, and would it be on Ceramics side or Animania?

Other milks are: Holsein, Friesian and Sheep.

Cheers,
SC

**Comment by KnightMiner** [comment]
I could possibly add support on my side, but it would be a hardcored check. An option on their side would be to change milking to check for any fluid container and full it instead of checking for vanilla buckets. They cluld even include a fluid contaoner whitelist (by config or IMC) if they want to prevent just any container from working.

**Comment by SeriousCreeper** [comment]
Hey,

i see, that makes sense. Pinging @capnkirok! 

-SC

**Comment by KnightMiner** [comment]
The issue on Animania's tracker was closed as added, so I will assume this works now and can be closed.

**Comment by capnkirok** [comment]
Cheers!
