### ISSUE TITLE
[Suggestion] Colored Armor + more

### ISSUE THREAD

**Issue by InkDragon** [KnightMiner/Ceramics#3]
I'd like to suggest adding the ability to dye the armor, like leather.

I'd also like to suggest a simple clay watering can.

As well as the potential addition of Porcelain Clay and Porcelain blocks. The clay can be oredictionatiaried to work with other mods that use porcelain(ex nihilo). The blocks function similar to harden clay but produce truer colors. Porcelain could also be used to create plates, mugs and bowls.

I'm not sure if jaquadro has abandoned Modular Flower Pots/ Garden Stuff but if so and they are willing to allow someone else to take over; their pots would fit in thematically with your mod.

I'd like to suggest more but I don't know what you have planned. I do however actually have real world experience with ceramics if you are in need of real world examples of cool things you can do with clay

**Comment by KnightMiner** [comment]
Colored armor I don't think I will do. Leather armor already has that as its main feature and I feel adding that to clay defeats the purpose of leather since leather is already more expensive. I may change my mind later down the road, but for now I am going to go with no.

No to the watering can, I never liked the idea of free tick acceleration. I feel that defeats the purpose of bone meal and other fertilizers.

I like the idea of porcelain clay, I've actually [partially implemented it](http://i.imgur.com/ddAneCb.png) to see how it looks in game - middle and barrels are porcelain clay, top row of blocks is normal clay, and bottom is wool. I won't be adding plates, mugs, etc. though as I feel purely decorative items fit better in another mod (I want just basic building blocks or functional blocks), but feel free to make them using Chisel and Bits with porcelain clay instead :)

Adding large flower pots is something I am considering, but yeah I don't want to add it if garden stuff is updated. I might try to contact jaquadro to see what his plans are.

----

Overall I don't have too many plans, so feel free to suggest more ideas. Just remember it tends to be themed towards functional items that are useful early to mid-game.

**Comment by InkDragon** [comment]
Thats reasonable for the clay armor.

The suggestion for the watering can was mostly for easily game before players can really get a mob farm up and running. It could have a limited durability it help offset the acceleration, but I understand the reasoning behind it.

I love the progress you have with the porcelain clay.

I'd definitely suggest contacting them, even if they plan to update there is no reason the two of you could work together to have some interplay between the two mods. Same potentially with Building Bricks.

unfortunately most items made with clay in the real world tend towards what would be decoration or more awkward to implement in minecraft. It'd be one thing to make things like tiles(clay carpets) or pressure plates, and another to create something like pipes or kilns.

**Comment by KnightMiner** [comment]
Closing in favor of #26
