### ISSUE TITLE
fluid gets stuck in dead branches of fluid channels

### ISSUE THREAD

**Issue by EnderiumSmith** [KnightMiner/Ceramics#37]
if you arrange channels in a tree when a container fills up fluid will get stuck on that branch so the last container wont fill up. this can be a problem when multiple fluids are supposed to flow. for example with a tinkers smeltery you dont want a nugget stuck in each casting table preventing the next fluid from flowing. a way to fix it is to make them work like the TE fluiducts.

**Comment by KnightMiner** [comment]
Please post a screenshot of what you mean.

It sounds like you are assuming the channels do something they are not designed to do. Channels are designed to be dumb fluid pipes, they simply output fluids to the next spot with no look ahead. If you were expecting something smart like TE fluiducts, then use TE fluiducts. What you probably need is an overflow system. Channels will allow fluid to pass over a tank if the tank below is full, so just connect the line after the tank back to the smeltery.

**Comment by KnightMiner** [comment]
Closing for lack of information.

I will leave with the reminder that channels are not designed to be "smart", they just flow any direction you allow them, so if there is a dead end it will fill until its full, not stop because its a dead end. Take this into account when designing channel networks, and consider setting up an overflow system which will flow down until full.
