### ISSUE TITLE
OreDict

### ISSUE THREAD

**Issue by Sunekaer** [KnightMiner/Ceramics#45]
Hey 

I have a problem with OreDict on your clay buckets in Stoneblock. 

Adding:
```
 <ore:listAlllava>.add(<ceramics:clay_bucket>.withTag({fluids: {FluidName: "lava", Amount: 1000}}));
<ore:listAllwater>.add(<ceramics:clay_bucket>.withTag({fluids: {FluidName: "water", Amount: 1000}}));
```
Will cause an empty Clay Bucket to have both Ore Dict tags.

forge 2796
Ceramics-1.12-1.3.6.jar

**Comment by KnightMiner** [comment]
The oredictionary does not work with NBT, do not try. The proper way to make the clay buckets work is the recipe to accept a fluid container rather than an oredict entry. Immersive Engineering does this with their treated wood and my clay buckets work fine, and last I checked CraftTweaker supports adding the same type of recipe.
