### ISSUE TITLE
Implementation With My Mod

### ISSUE THREAD

**Issue by llchris** [KnightMiner/Ceramics#48]
Hello. I added a cauldron in minecraft with my mod and seems that it does not support the clay bucket. I looked into your ItemClayBucket class, and i wrote a code similiar to yours in interactCauldron in a FillBucketEvent. I have a question. I actually cant get the private methods used to place water in world with the clay bucket. I hope my text is clear. Thanks for reading.
Bye.

**Comment by KnightMiner** [comment]
You should really not do this the way my bucket interacts with the cauldron, ideally what you should do is make your custom cauldron act as a fluid tank (one that only returns water of course). This will make it compatible with any mod adding a custom bucket instead of just mine. See [this example from Inspirations](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/recipes/tileentity/TileCauldron.java#L441-L455) ([fluid handler class](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/recipes/tank/CauldronTank.java)).

If your custom cauldron does not have a tile entity, your next good solution is to make it generic to fluid containers in your onBlockActivated method. [LeatherWorks](https://github.com/MinecraftModDevelopmentMods/LeatherWorks/blob/master/src/main/java/panda/leatherworks/common/block/BlockBarrel.java#L199-L220) has a good example

**Comment by llchris** [comment]
Thank you for your reply.
