### ISSUE TITLE
Game Crashes with Channels

### ISSUE THREAD

**Issue by LurkingFox6539** [KnightMiner/Ceramics#73]
When leading a channel off of a container, the game crashes if you try to set it to flowing down without another channel underneath of it. I tested this several times and it happens with both terracotta and porcelain versions. This also happens when shift clicking instead of placing the channel underneath of it.

**Comment by KnightMiner** [comment]
Crash report or it didn't happen. In other words, never crashed for me.

**Comment by LurkingFox6539** [comment]
[crash-2021-02-11_20.09.25-client.txt](https://github.com/KnightMiner/Ceramics/files/5969487/crash-2021-02-11_20.09.25-client.txt)

**Comment by Shann42** [comment]
I'm new to GitHub (this is my first post) so I hope I'm following protocol by adding to this topic instead of starting a new one.  I'm having the same crashing problem exactly which is a shame because I love the water channels.  I am using the latest Valhelsia 3 (3.1.9) modpack and added Ceramics with Mantle so I knew I was pushing my luck.  I've added a few other mods to Val 3 without any problems, but others don't work out as well - it's hit and miss.  I have not tried running an instance (via MultiMC) of Ceramics without any other mods, so I can't say it's a problem with Ceramics or one of the other 200+ mods in Val 3!  Here's my crash report.  Love your mod, I'm making a much smaller modpack and I'm betting Ceramics will work fine there.  Thank you for taking the time to create this!

[crash-2021-03-10_09.33.32-client.txt](https://github.com/KnightMiner/Ceramics/files/6116788/crash-2021-03-10_09.33.32-client.txt)

**Comment by KnightMiner** [comment]
I don't think this is a modpack problem. This crash report looks like one of those where I wonder why it never happened in testing. I just have not had time to fix it yet.

**Comment by KnightMiner** [comment]
Fixed in 1.6.2. For the record, this crash is from right clicking the bottom of a block with a channel. Not related to adjusting connections, you just were trying to do that when the game interpreted you wanting to place the block.
